import type { Metadata } from "next";
import localFont from "next/font/local";
import './globals.css';
import ClientWrapper from "./ClientWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Drive Courses - Faites vos courses en ligne</title>
          <meta name="description" content="Commandez vos courses en ligne et récupérez-les à votre drive. Livraison rapide et facile." />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ClientWrapper>
      <header className="bg-teal-500 text-white p-8 text-center rounded-b-lg shadow-md">
      <h1 className="text-4xl font-bold mb-4">Bienvenue sur le GIGA Drive !</h1>
      <p className="text-lg mb-8">Vos courses en ligne, prêtes à être récupérées ou livrées en un clin d'œil.</p>
    </header>
        {children}

    <footer className='footer'>
        <p>Made with 🤬 by 🦧</p>
    </footer>
      </ClientWrapper>
      </body>
    </html>
  );
}
